//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;

namespace sap_soa_obroty._ws_HelpDeskDomino {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:DefaultNamespace", ConfigurationName="_ws_HelpDeskDomino.InfZglPort")]
    public interface InfZglPort {
        
        // CODEGEN: Parameter 'POKAZZGLOSZENIAODPReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="POKAZZGLOSZENIAODP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="POKAZZGLOSZENIAODPReturn")]
        sap_soa_obroty._ws_HelpDeskDomino.POKAZZGLOSZENIAODPResponse POKAZZGLOSZENIAODP(sap_soa_obroty._ws_HelpDeskDomino.POKAZZGLOSZENIAODPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="POKAZZGLOSZENIAODP", ReplyAction="*")]
        System.Threading.Tasks.Task<sap_soa_obroty._ws_HelpDeskDomino.POKAZZGLOSZENIAODPResponse> POKAZZGLOSZENIAODPAsync(sap_soa_obroty._ws_HelpDeskDomino.POKAZZGLOSZENIAODPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="STATUSZGLOSZENIA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="STATUSZGLOSZENIAReturn")]
        sap_soa_obroty._ws_HelpDeskDomino.DANEZGLOSZENIA STATUSZGLOSZENIA(string NUMER_ZGLOSZENIA);
        
        [System.ServiceModel.OperationContractAttribute(Action="STATUSZGLOSZENIA", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="STATUSZGLOSZENIAReturn")]
        System.Threading.Tasks.Task<sap_soa_obroty._ws_HelpDeskDomino.DANEZGLOSZENIA> STATUSZGLOSZENIAAsync(string NUMER_ZGLOSZENIA);
        
        [System.ServiceModel.OperationContractAttribute(Action="DODAJKOMENTARZ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DODAJKOMENTARZReturn")]
        object DODAJKOMENTARZ(string NUMER_ZGLOSZENIA, string KOMENTARZ);
        
        [System.ServiceModel.OperationContractAttribute(Action="DODAJKOMENTARZ", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DODAJKOMENTARZReturn")]
        System.Threading.Tasks.Task<object> DODAJKOMENTARZAsync(string NUMER_ZGLOSZENIA, string KOMENTARZ);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class POZYCJALISTY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dATAField;
        
        private string nUMERField;
        
        private string zGLASZAJACYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DATA {
            get {
                return this.dATAField;
            }
            set {
                this.dATAField = value;
                this.RaisePropertyChanged("DATA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NUMER {
            get {
                return this.nUMERField;
            }
            set {
                this.nUMERField = value;
                this.RaisePropertyChanged("NUMER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZGLASZAJACY {
            get {
                return this.zGLASZAJACYField;
            }
            set {
                this.zGLASZAJACYField = value;
                this.RaisePropertyChanged("ZGLASZAJACY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class DANEZGLOSZENIA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oPISField;
        
        private string sTATUSField;
        
        private string oDPOWIEDZIALNYField;
        
        private string bLADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OPIS {
            get {
                return this.oPISField;
            }
            set {
                this.oPISField = value;
                this.RaisePropertyChanged("OPIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ODPOWIEDZIALNY {
            get {
                return this.oDPOWIEDZIALNYField;
            }
            set {
                this.oDPOWIEDZIALNYField = value;
                this.RaisePropertyChanged("ODPOWIEDZIALNY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BLAD {
            get {
                return this.bLADField;
            }
            set {
                this.bLADField = value;
                this.RaisePropertyChanged("BLAD");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POKAZZGLOSZENIAODP", WrapperNamespace="urn:DefaultNamespace", IsWrapped=true)]
    public partial class POKAZZGLOSZENIAODPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ODPOWIEDZIALNY;
        
        public POKAZZGLOSZENIAODPRequest() {
        }
        
        public POKAZZGLOSZENIAODPRequest(string ODPOWIEDZIALNY) {
            this.ODPOWIEDZIALNY = ODPOWIEDZIALNY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="POKAZZGLOSZENIAODPResponse", WrapperNamespace="urn:DefaultNamespace", IsWrapped=true)]
    public partial class POKAZZGLOSZENIAODPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("POZYCJA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sap_soa_obroty._ws_HelpDeskDomino.POZYCJALISTY[] POKAZZGLOSZENIAODPReturn;
        
        public POKAZZGLOSZENIAODPResponse() {
        }
        
        public POKAZZGLOSZENIAODPResponse(sap_soa_obroty._ws_HelpDeskDomino.POZYCJALISTY[] POKAZZGLOSZENIAODPReturn) {
            this.POKAZZGLOSZENIAODPReturn = POKAZZGLOSZENIAODPReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InfZglPortChannel : sap_soa_obroty._ws_HelpDeskDomino.InfZglPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InfZglPortClient : System.ServiceModel.ClientBase<sap_soa_obroty._ws_HelpDeskDomino.InfZglPort>, sap_soa_obroty._ws_HelpDeskDomino.InfZglPort {
        
        public InfZglPortClient() {
        }
        
        public InfZglPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InfZglPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfZglPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfZglPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sap_soa_obroty._ws_HelpDeskDomino.POKAZZGLOSZENIAODPResponse sap_soa_obroty._ws_HelpDeskDomino.InfZglPort.POKAZZGLOSZENIAODP(sap_soa_obroty._ws_HelpDeskDomino.POKAZZGLOSZENIAODPRequest request) {
            return base.Channel.POKAZZGLOSZENIAODP(request);
        }
        
        public sap_soa_obroty._ws_HelpDeskDomino.POZYCJALISTY[] POKAZZGLOSZENIAODP(string ODPOWIEDZIALNY) {
            sap_soa_obroty._ws_HelpDeskDomino.POKAZZGLOSZENIAODPRequest inValue = new sap_soa_obroty._ws_HelpDeskDomino.POKAZZGLOSZENIAODPRequest();
            inValue.ODPOWIEDZIALNY = ODPOWIEDZIALNY;
            sap_soa_obroty._ws_HelpDeskDomino.POKAZZGLOSZENIAODPResponse retVal = ((sap_soa_obroty._ws_HelpDeskDomino.InfZglPort)(this)).POKAZZGLOSZENIAODP(inValue);
            return retVal.POKAZZGLOSZENIAODPReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sap_soa_obroty._ws_HelpDeskDomino.POKAZZGLOSZENIAODPResponse> sap_soa_obroty._ws_HelpDeskDomino.InfZglPort.POKAZZGLOSZENIAODPAsync(sap_soa_obroty._ws_HelpDeskDomino.POKAZZGLOSZENIAODPRequest request) {
            return base.Channel.POKAZZGLOSZENIAODPAsync(request);
        }
        
        public System.Threading.Tasks.Task<sap_soa_obroty._ws_HelpDeskDomino.POKAZZGLOSZENIAODPResponse> POKAZZGLOSZENIAODPAsync(string ODPOWIEDZIALNY) {
            sap_soa_obroty._ws_HelpDeskDomino.POKAZZGLOSZENIAODPRequest inValue = new sap_soa_obroty._ws_HelpDeskDomino.POKAZZGLOSZENIAODPRequest();
            inValue.ODPOWIEDZIALNY = ODPOWIEDZIALNY;
            return ((sap_soa_obroty._ws_HelpDeskDomino.InfZglPort)(this)).POKAZZGLOSZENIAODPAsync(inValue);
        }
        
        public sap_soa_obroty._ws_HelpDeskDomino.DANEZGLOSZENIA STATUSZGLOSZENIA(string NUMER_ZGLOSZENIA) {
            return base.Channel.STATUSZGLOSZENIA(NUMER_ZGLOSZENIA);
        }
        
        public System.Threading.Tasks.Task<sap_soa_obroty._ws_HelpDeskDomino.DANEZGLOSZENIA> STATUSZGLOSZENIAAsync(string NUMER_ZGLOSZENIA) {
            return base.Channel.STATUSZGLOSZENIAAsync(NUMER_ZGLOSZENIA);
        }
        
        public object DODAJKOMENTARZ(string NUMER_ZGLOSZENIA, string KOMENTARZ) {
            return base.Channel.DODAJKOMENTARZ(NUMER_ZGLOSZENIA, KOMENTARZ);
        }
        
        public System.Threading.Tasks.Task<object> DODAJKOMENTARZAsync(string NUMER_ZGLOSZENIA, string KOMENTARZ) {
            return base.Channel.DODAJKOMENTARZAsync(NUMER_ZGLOSZENIA, KOMENTARZ);
        }
    }
}
