//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace sap_soa_obroty.pl.aquael.domino {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Net;
    using System.Text;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InfZglPortNameSoapBinding", Namespace="urn:DefaultNamespace")]
    public partial class InfZglElementName : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback STATUSZGLOSZENIAOperationCompleted;
        
        private System.Threading.SendOrPostCallback DODAJKOMENTARZOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InfZglElementName() {
            this.Url = global::sap_soa_obroty.Properties.Settings.Default.sap_soa_obroty_pl_aquael_domino_InfZglElementName;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }


        protected override System.Net.WebRequest GetWebRequest(Uri uri)
        {
            HttpWebRequest request;
            request = (HttpWebRequest)base.GetWebRequest(uri);

            if (PreAuthenticate)
            {
                NetworkCredential networkCredentials =
                    Credentials.GetCredential(uri, "Basic");

                if (networkCredentials != null)
                {
                    byte[] credentialBuffer = new UTF8Encoding().GetBytes(
                        networkCredentials.UserName + ":" +
                        networkCredentials.Password);
                    request.Headers["Authorization"] =
                        "Basic" + Convert.ToBase64String(credentialBuffer);
                }
                else
                {
                    throw new ApplicationException("No network credentials");
                }
            }
            return request;
        }

        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event STATUSZGLOSZENIACompletedEventHandler STATUSZGLOSZENIACompleted;
        
        /// <remarks/>
        public event DODAJKOMENTARZCompletedEventHandler DODAJKOMENTARZCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("STATUSZGLOSZENIA", RequestNamespace="urn:DefaultNamespace", ResponseNamespace="urn:DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("STATUSZGLOSZENIAReturn")]
        public DANEZGLOSZENIA STATUSZGLOSZENIA(string NUMER_ZGLOSZENIA) {
            object[] results = this.Invoke("STATUSZGLOSZENIA", new object[] {
                        NUMER_ZGLOSZENIA});
            return ((DANEZGLOSZENIA)(results[0]));
        }
        
        /// <remarks/>
        public void STATUSZGLOSZENIAAsync(string NUMER_ZGLOSZENIA) {
            this.STATUSZGLOSZENIAAsync(NUMER_ZGLOSZENIA, null);
        }
        
        /// <remarks/>
        public void STATUSZGLOSZENIAAsync(string NUMER_ZGLOSZENIA, object userState) {
            if ((this.STATUSZGLOSZENIAOperationCompleted == null)) {
                this.STATUSZGLOSZENIAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTATUSZGLOSZENIAOperationCompleted);
            }
            this.InvokeAsync("STATUSZGLOSZENIA", new object[] {
                        NUMER_ZGLOSZENIA}, this.STATUSZGLOSZENIAOperationCompleted, userState);
        }
        
        private void OnSTATUSZGLOSZENIAOperationCompleted(object arg) {
            if ((this.STATUSZGLOSZENIACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STATUSZGLOSZENIACompleted(this, new STATUSZGLOSZENIACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("DODAJKOMENTARZ", RequestNamespace="urn:DefaultNamespace", ResponseNamespace="urn:DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("DODAJKOMENTARZReturn")]
        public object DODAJKOMENTARZ(string NUMER_ZGLOSZENIA, string KOMENTARZ) {
            object[] results = this.Invoke("DODAJKOMENTARZ", new object[] {
                        NUMER_ZGLOSZENIA,
                        KOMENTARZ});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void DODAJKOMENTARZAsync(string NUMER_ZGLOSZENIA, string KOMENTARZ) {
            this.DODAJKOMENTARZAsync(NUMER_ZGLOSZENIA, KOMENTARZ, null);
        }
        
        /// <remarks/>
        public void DODAJKOMENTARZAsync(string NUMER_ZGLOSZENIA, string KOMENTARZ, object userState) {
            if ((this.DODAJKOMENTARZOperationCompleted == null)) {
                this.DODAJKOMENTARZOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDODAJKOMENTARZOperationCompleted);
            }
            this.InvokeAsync("DODAJKOMENTARZ", new object[] {
                        NUMER_ZGLOSZENIA,
                        KOMENTARZ}, this.DODAJKOMENTARZOperationCompleted, userState);
        }
        
        private void OnDODAJKOMENTARZOperationCompleted(object arg) {
            if ((this.DODAJKOMENTARZCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DODAJKOMENTARZCompleted(this, new DODAJKOMENTARZCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class DANEZGLOSZENIA {
        
        private string oPISField;
        
        private string sTATUSField;
        
        private string oDPOWIEDZIALNYField;
        
        private string bLADField;
        
        /// <remarks/>
        public string OPIS {
            get {
                return this.oPISField;
            }
            set {
                this.oPISField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string ODPOWIEDZIALNY {
            get {
                return this.oDPOWIEDZIALNYField;
            }
            set {
                this.oDPOWIEDZIALNYField = value;
            }
        }
        
        /// <remarks/>
        public string BLAD {
            get {
                return this.bLADField;
            }
            set {
                this.bLADField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STATUSZGLOSZENIACompletedEventHandler(object sender, STATUSZGLOSZENIACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STATUSZGLOSZENIACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STATUSZGLOSZENIACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DANEZGLOSZENIA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DANEZGLOSZENIA)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DODAJKOMENTARZCompletedEventHandler(object sender, DODAJKOMENTARZCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DODAJKOMENTARZCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DODAJKOMENTARZCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591