//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sap_soa_obroty.SOAPSAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SOAPSAP.ZPK_CRM_RAPORTY")]
    public interface ZPK_CRM_RAPORTY {
        
        // CODEGEN: Generating message contract since the operation REVE_AGGREGATION is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONResponse1 REVE_AGGREGATION(sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONResponse1> REVE_AGGREGATIONAsync(sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONRequest request);
        
        // CODEGEN: Generating message contract since the operation REVE_AGGREGATION_KUNRG is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGResponse1 REVE_AGGREGATION_KUNRG(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGResponse1> REVE_AGGREGATION_KUNRGAsync(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGRequest request);
        
        // CODEGEN: Generating message contract since the operation REVE_AGGREGATION_KUNWE is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWEResponse1 REVE_AGGREGATION_KUNWE(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWEResponse1> REVE_AGGREGATION_KUNWEAsync(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWERequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class REVE_AGGREGATION : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] iT_KNDNRField;
        
        private string iV_KNDNR_FROMField;
        
        private string iV_KNDNR_TOField;
        
        private ZPK_S_PERIOD iV_PERIOD_FROMField;
        
        private ZPK_S_PERIOD iV_PERIOD_TOField;
        
        private string iV_VKORGField;
        
        private string iV_VTWEGField;
        
        private string iV_WERKSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] IT_KNDNR {
            get {
                return this.iT_KNDNRField;
            }
            set {
                this.iT_KNDNRField = value;
                this.RaisePropertyChanged("IT_KNDNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IV_KNDNR_FROM {
            get {
                return this.iV_KNDNR_FROMField;
            }
            set {
                this.iV_KNDNR_FROMField = value;
                this.RaisePropertyChanged("IV_KNDNR_FROM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IV_KNDNR_TO {
            get {
                return this.iV_KNDNR_TOField;
            }
            set {
                this.iV_KNDNR_TOField = value;
                this.RaisePropertyChanged("IV_KNDNR_TO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ZPK_S_PERIOD IV_PERIOD_FROM {
            get {
                return this.iV_PERIOD_FROMField;
            }
            set {
                this.iV_PERIOD_FROMField = value;
                this.RaisePropertyChanged("IV_PERIOD_FROM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ZPK_S_PERIOD IV_PERIOD_TO {
            get {
                return this.iV_PERIOD_TOField;
            }
            set {
                this.iV_PERIOD_TOField = value;
                this.RaisePropertyChanged("IV_PERIOD_TO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string IV_VKORG {
            get {
                return this.iV_VKORGField;
            }
            set {
                this.iV_VKORGField = value;
                this.RaisePropertyChanged("IV_VKORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string IV_VTWEG {
            get {
                return this.iV_VTWEGField;
            }
            set {
                this.iV_VTWEGField = value;
                this.RaisePropertyChanged("IV_VTWEG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string IV_WERKS {
            get {
                return this.iV_WERKSField;
            }
            set {
                this.iV_WERKSField = value;
                this.RaisePropertyChanged("IV_WERKS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPK_S_PERIOD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string yEARField;
        
        private string mONTHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string YEAR {
            get {
                return this.yEARField;
            }
            set {
                this.yEARField = value;
                this.RaisePropertyChanged("YEAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MONTH {
            get {
                return this.mONTHField;
            }
            set {
                this.mONTHField = value;
                this.RaisePropertyChanged("MONTH");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPK_S_REVE_KUNRG_RESULT_EXTWG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vKORGField;
        
        private string vTWEGField;
        
        private string wERKSField;
        
        private string kUNRGField;
        
        private string eXTWGField;
        
        private decimal eRLOSField;
        
        private decimal eRLOS_INCL_DISCNTField;
        
        private string wAERSField;
        
        private decimal vV001Field;
        
        private decimal vV002Field;
        
        private decimal vV003Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VKORG {
            get {
                return this.vKORGField;
            }
            set {
                this.vKORGField = value;
                this.RaisePropertyChanged("VKORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VTWEG {
            get {
                return this.vTWEGField;
            }
            set {
                this.vTWEGField = value;
                this.RaisePropertyChanged("VTWEG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string KUNRG {
            get {
                return this.kUNRGField;
            }
            set {
                this.kUNRGField = value;
                this.RaisePropertyChanged("KUNRG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EXTWG {
            get {
                return this.eXTWGField;
            }
            set {
                this.eXTWGField = value;
                this.RaisePropertyChanged("EXTWG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal ERLOS {
            get {
                return this.eRLOSField;
            }
            set {
                this.eRLOSField = value;
                this.RaisePropertyChanged("ERLOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal ERLOS_INCL_DISCNT {
            get {
                return this.eRLOS_INCL_DISCNTField;
            }
            set {
                this.eRLOS_INCL_DISCNTField = value;
                this.RaisePropertyChanged("ERLOS_INCL_DISCNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
                this.RaisePropertyChanged("WAERS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal VV001 {
            get {
                return this.vV001Field;
            }
            set {
                this.vV001Field = value;
                this.RaisePropertyChanged("VV001");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal VV002 {
            get {
                return this.vV002Field;
            }
            set {
                this.vV002Field = value;
                this.RaisePropertyChanged("VV002");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal VV003 {
            get {
                return this.vV003Field;
            }
            set {
                this.vV003Field = value;
                this.RaisePropertyChanged("VV003");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPK_S_REVE_KUNRG_RESULT_AQ2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vKORGField;
        
        private string vTWEGField;
        
        private string wERKSField;
        
        private string kUNRGField;
        
        private string zZM_AQ2Field;
        
        private decimal eRLOSField;
        
        private decimal eRLOS_INCL_DISCNTField;
        
        private string wAERSField;
        
        private decimal vV001Field;
        
        private decimal vV002Field;
        
        private decimal vV003Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VKORG {
            get {
                return this.vKORGField;
            }
            set {
                this.vKORGField = value;
                this.RaisePropertyChanged("VKORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VTWEG {
            get {
                return this.vTWEGField;
            }
            set {
                this.vTWEGField = value;
                this.RaisePropertyChanged("VTWEG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string KUNRG {
            get {
                return this.kUNRGField;
            }
            set {
                this.kUNRGField = value;
                this.RaisePropertyChanged("KUNRG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZZM_AQ2 {
            get {
                return this.zZM_AQ2Field;
            }
            set {
                this.zZM_AQ2Field = value;
                this.RaisePropertyChanged("ZZM_AQ2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal ERLOS {
            get {
                return this.eRLOSField;
            }
            set {
                this.eRLOSField = value;
                this.RaisePropertyChanged("ERLOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal ERLOS_INCL_DISCNT {
            get {
                return this.eRLOS_INCL_DISCNTField;
            }
            set {
                this.eRLOS_INCL_DISCNTField = value;
                this.RaisePropertyChanged("ERLOS_INCL_DISCNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
                this.RaisePropertyChanged("WAERS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal VV001 {
            get {
                return this.vV001Field;
            }
            set {
                this.vV001Field = value;
                this.RaisePropertyChanged("VV001");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal VV002 {
            get {
                return this.vV002Field;
            }
            set {
                this.vV002Field = value;
                this.RaisePropertyChanged("VV002");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal VV003 {
            get {
                return this.vV003Field;
            }
            set {
                this.vV003Field = value;
                this.RaisePropertyChanged("VV003");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPK_S_REVE_KUNRG_RESULT_AQ10 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vKORGField;
        
        private string vTWEGField;
        
        private string wERKSField;
        
        private string kUNRGField;
        
        private string zZM_AQ2Field;
        
        private string zZM_AQ10Field;
        
        private decimal eRLOSField;
        
        private decimal eRLOS_INCL_DISCNTField;
        
        private string wAERSField;
        
        private decimal vV001Field;
        
        private decimal vV002Field;
        
        private decimal vV003Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VKORG {
            get {
                return this.vKORGField;
            }
            set {
                this.vKORGField = value;
                this.RaisePropertyChanged("VKORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VTWEG {
            get {
                return this.vTWEGField;
            }
            set {
                this.vTWEGField = value;
                this.RaisePropertyChanged("VTWEG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string KUNRG {
            get {
                return this.kUNRGField;
            }
            set {
                this.kUNRGField = value;
                this.RaisePropertyChanged("KUNRG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZZM_AQ2 {
            get {
                return this.zZM_AQ2Field;
            }
            set {
                this.zZM_AQ2Field = value;
                this.RaisePropertyChanged("ZZM_AQ2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZZM_AQ10 {
            get {
                return this.zZM_AQ10Field;
            }
            set {
                this.zZM_AQ10Field = value;
                this.RaisePropertyChanged("ZZM_AQ10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal ERLOS {
            get {
                return this.eRLOSField;
            }
            set {
                this.eRLOSField = value;
                this.RaisePropertyChanged("ERLOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal ERLOS_INCL_DISCNT {
            get {
                return this.eRLOS_INCL_DISCNTField;
            }
            set {
                this.eRLOS_INCL_DISCNTField = value;
                this.RaisePropertyChanged("ERLOS_INCL_DISCNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
                this.RaisePropertyChanged("WAERS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal VV001 {
            get {
                return this.vV001Field;
            }
            set {
                this.vV001Field = value;
                this.RaisePropertyChanged("VV001");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal VV002 {
            get {
                return this.vV002Field;
            }
            set {
                this.vV002Field = value;
                this.RaisePropertyChanged("VV002");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal VV003 {
            get {
                return this.vV003Field;
            }
            set {
                this.vV003Field = value;
                this.RaisePropertyChanged("VV003");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPK_S_REVE_RESULT_EXTWG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vKORGField;
        
        private string vTWEGField;
        
        private string wERKSField;
        
        private string kUNNRField;
        
        private string eXTWGField;
        
        private decimal eRLOSField;
        
        private decimal eRLOS_INCL_DISCNTField;
        
        private string wAERSField;
        
        private decimal vV001Field;
        
        private decimal vV002Field;
        
        private decimal vV003Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VKORG {
            get {
                return this.vKORGField;
            }
            set {
                this.vKORGField = value;
                this.RaisePropertyChanged("VKORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VTWEG {
            get {
                return this.vTWEGField;
            }
            set {
                this.vTWEGField = value;
                this.RaisePropertyChanged("VTWEG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string KUNNR {
            get {
                return this.kUNNRField;
            }
            set {
                this.kUNNRField = value;
                this.RaisePropertyChanged("KUNNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string EXTWG {
            get {
                return this.eXTWGField;
            }
            set {
                this.eXTWGField = value;
                this.RaisePropertyChanged("EXTWG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal ERLOS {
            get {
                return this.eRLOSField;
            }
            set {
                this.eRLOSField = value;
                this.RaisePropertyChanged("ERLOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal ERLOS_INCL_DISCNT {
            get {
                return this.eRLOS_INCL_DISCNTField;
            }
            set {
                this.eRLOS_INCL_DISCNTField = value;
                this.RaisePropertyChanged("ERLOS_INCL_DISCNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
                this.RaisePropertyChanged("WAERS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal VV001 {
            get {
                return this.vV001Field;
            }
            set {
                this.vV001Field = value;
                this.RaisePropertyChanged("VV001");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal VV002 {
            get {
                return this.vV002Field;
            }
            set {
                this.vV002Field = value;
                this.RaisePropertyChanged("VV002");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal VV003 {
            get {
                return this.vV003Field;
            }
            set {
                this.vV003Field = value;
                this.RaisePropertyChanged("VV003");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPK_S_REVE_RESULT_AQ2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vKORGField;
        
        private string vTWEGField;
        
        private string wERKSField;
        
        private string kUNNRField;
        
        private string zZM_AQ2Field;
        
        private decimal eRLOSField;
        
        private decimal eRLOS_INCL_DISCNTField;
        
        private string wAERSField;
        
        private decimal vV001Field;
        
        private decimal vV002Field;
        
        private decimal vV003Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VKORG {
            get {
                return this.vKORGField;
            }
            set {
                this.vKORGField = value;
                this.RaisePropertyChanged("VKORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VTWEG {
            get {
                return this.vTWEGField;
            }
            set {
                this.vTWEGField = value;
                this.RaisePropertyChanged("VTWEG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string KUNNR {
            get {
                return this.kUNNRField;
            }
            set {
                this.kUNNRField = value;
                this.RaisePropertyChanged("KUNNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZZM_AQ2 {
            get {
                return this.zZM_AQ2Field;
            }
            set {
                this.zZM_AQ2Field = value;
                this.RaisePropertyChanged("ZZM_AQ2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal ERLOS {
            get {
                return this.eRLOSField;
            }
            set {
                this.eRLOSField = value;
                this.RaisePropertyChanged("ERLOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal ERLOS_INCL_DISCNT {
            get {
                return this.eRLOS_INCL_DISCNTField;
            }
            set {
                this.eRLOS_INCL_DISCNTField = value;
                this.RaisePropertyChanged("ERLOS_INCL_DISCNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
                this.RaisePropertyChanged("WAERS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal VV001 {
            get {
                return this.vV001Field;
            }
            set {
                this.vV001Field = value;
                this.RaisePropertyChanged("VV001");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal VV002 {
            get {
                return this.vV002Field;
            }
            set {
                this.vV002Field = value;
                this.RaisePropertyChanged("VV002");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal VV003 {
            get {
                return this.vV003Field;
            }
            set {
                this.vV003Field = value;
                this.RaisePropertyChanged("VV003");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPK_S_REVE_RESULT_AQ10 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vKORGField;
        
        private string vTWEGField;
        
        private string wERKSField;
        
        private string kUNNRField;
        
        private string zZM_AQ2Field;
        
        private string zZM_AQ10Field;
        
        private decimal eRLOSField;
        
        private decimal eRLOS_INCL_DISCNTField;
        
        private string wAERSField;
        
        private decimal vV001Field;
        
        private decimal vV002Field;
        
        private decimal vV003Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VKORG {
            get {
                return this.vKORGField;
            }
            set {
                this.vKORGField = value;
                this.RaisePropertyChanged("VKORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VTWEG {
            get {
                return this.vTWEGField;
            }
            set {
                this.vTWEGField = value;
                this.RaisePropertyChanged("VTWEG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string KUNNR {
            get {
                return this.kUNNRField;
            }
            set {
                this.kUNNRField = value;
                this.RaisePropertyChanged("KUNNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZZM_AQ2 {
            get {
                return this.zZM_AQ2Field;
            }
            set {
                this.zZM_AQ2Field = value;
                this.RaisePropertyChanged("ZZM_AQ2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZZM_AQ10 {
            get {
                return this.zZM_AQ10Field;
            }
            set {
                this.zZM_AQ10Field = value;
                this.RaisePropertyChanged("ZZM_AQ10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal ERLOS {
            get {
                return this.eRLOSField;
            }
            set {
                this.eRLOSField = value;
                this.RaisePropertyChanged("ERLOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal ERLOS_INCL_DISCNT {
            get {
                return this.eRLOS_INCL_DISCNTField;
            }
            set {
                this.eRLOS_INCL_DISCNTField = value;
                this.RaisePropertyChanged("ERLOS_INCL_DISCNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
                this.RaisePropertyChanged("WAERS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal VV001 {
            get {
                return this.vV001Field;
            }
            set {
                this.vV001Field = value;
                this.RaisePropertyChanged("VV001");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal VV002 {
            get {
                return this.vV002Field;
            }
            set {
                this.vV002Field = value;
                this.RaisePropertyChanged("VV002");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal VV003 {
            get {
                return this.vV003Field;
            }
            set {
                this.vV003Field = value;
                this.RaisePropertyChanged("VV003");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class REVE_AGGREGATIONResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZPK_S_REVE_RESULT_AQ10[] eT_AQ10Field;
        
        private ZPK_S_REVE_RESULT_AQ2[] eT_AQ2Field;
        
        private ZPK_S_REVE_RESULT_EXTWG[] eT_EXTWGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZPK_S_REVE_RESULT_AQ10[] ET_AQ10 {
            get {
                return this.eT_AQ10Field;
            }
            set {
                this.eT_AQ10Field = value;
                this.RaisePropertyChanged("ET_AQ10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZPK_S_REVE_RESULT_AQ2[] ET_AQ2 {
            get {
                return this.eT_AQ2Field;
            }
            set {
                this.eT_AQ2Field = value;
                this.RaisePropertyChanged("ET_AQ2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZPK_S_REVE_RESULT_EXTWG[] ET_EXTWG {
            get {
                return this.eT_EXTWGField;
            }
            set {
                this.eT_EXTWGField = value;
                this.RaisePropertyChanged("ET_EXTWG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class REVE_AGGREGATIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public sap_soa_obroty.SOAPSAP.REVE_AGGREGATION REVE_AGGREGATION;
        
        public REVE_AGGREGATIONRequest() {
        }
        
        public REVE_AGGREGATIONRequest(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION REVE_AGGREGATION) {
            this.REVE_AGGREGATION = REVE_AGGREGATION;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class REVE_AGGREGATIONResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONResponse REVE_AGGREGATIONResponse;
        
        public REVE_AGGREGATIONResponse1() {
        }
        
        public REVE_AGGREGATIONResponse1(sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONResponse REVE_AGGREGATIONResponse) {
            this.REVE_AGGREGATIONResponse = REVE_AGGREGATIONResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class REVE_AGGREGATION_KUNRG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] iT_KUNRGField;
        
        private string[] iT_KUNWEField;
        
        private string iV_KUNRG_FROMField;
        
        private string iV_KUNRG_TOField;
        
        private string iV_KUNWE_FROMField;
        
        private string iV_KUNWE_TOField;
        
        private ZPK_S_PERIOD iV_PERIOD_FROMField;
        
        private ZPK_S_PERIOD iV_PERIOD_TOField;
        
        private string iV_VKORGField;
        
        private string iV_VTWEGField;
        
        private string iV_WERKSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] IT_KUNRG {
            get {
                return this.iT_KUNRGField;
            }
            set {
                this.iT_KUNRGField = value;
                this.RaisePropertyChanged("IT_KUNRG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] IT_KUNWE {
            get {
                return this.iT_KUNWEField;
            }
            set {
                this.iT_KUNWEField = value;
                this.RaisePropertyChanged("IT_KUNWE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IV_KUNRG_FROM {
            get {
                return this.iV_KUNRG_FROMField;
            }
            set {
                this.iV_KUNRG_FROMField = value;
                this.RaisePropertyChanged("IV_KUNRG_FROM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IV_KUNRG_TO {
            get {
                return this.iV_KUNRG_TOField;
            }
            set {
                this.iV_KUNRG_TOField = value;
                this.RaisePropertyChanged("IV_KUNRG_TO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IV_KUNWE_FROM {
            get {
                return this.iV_KUNWE_FROMField;
            }
            set {
                this.iV_KUNWE_FROMField = value;
                this.RaisePropertyChanged("IV_KUNWE_FROM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string IV_KUNWE_TO {
            get {
                return this.iV_KUNWE_TOField;
            }
            set {
                this.iV_KUNWE_TOField = value;
                this.RaisePropertyChanged("IV_KUNWE_TO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public ZPK_S_PERIOD IV_PERIOD_FROM {
            get {
                return this.iV_PERIOD_FROMField;
            }
            set {
                this.iV_PERIOD_FROMField = value;
                this.RaisePropertyChanged("IV_PERIOD_FROM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public ZPK_S_PERIOD IV_PERIOD_TO {
            get {
                return this.iV_PERIOD_TOField;
            }
            set {
                this.iV_PERIOD_TOField = value;
                this.RaisePropertyChanged("IV_PERIOD_TO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string IV_VKORG {
            get {
                return this.iV_VKORGField;
            }
            set {
                this.iV_VKORGField = value;
                this.RaisePropertyChanged("IV_VKORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string IV_VTWEG {
            get {
                return this.iV_VTWEGField;
            }
            set {
                this.iV_VTWEGField = value;
                this.RaisePropertyChanged("IV_VTWEG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string IV_WERKS {
            get {
                return this.iV_WERKSField;
            }
            set {
                this.iV_WERKSField = value;
                this.RaisePropertyChanged("IV_WERKS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class REVE_AGGREGATION_KUNRGResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZPK_S_REVE_RESULT_AQ10[] eT_AQ10Field;
        
        private ZPK_S_REVE_RESULT_AQ2[] eT_AQ2Field;
        
        private ZPK_S_REVE_RESULT_EXTWG[] eT_EXTWGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZPK_S_REVE_RESULT_AQ10[] ET_AQ10 {
            get {
                return this.eT_AQ10Field;
            }
            set {
                this.eT_AQ10Field = value;
                this.RaisePropertyChanged("ET_AQ10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZPK_S_REVE_RESULT_AQ2[] ET_AQ2 {
            get {
                return this.eT_AQ2Field;
            }
            set {
                this.eT_AQ2Field = value;
                this.RaisePropertyChanged("ET_AQ2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZPK_S_REVE_RESULT_EXTWG[] ET_EXTWG {
            get {
                return this.eT_EXTWGField;
            }
            set {
                this.eT_EXTWGField = value;
                this.RaisePropertyChanged("ET_EXTWG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class REVE_AGGREGATION_KUNRGRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRG REVE_AGGREGATION_KUNRG;
        
        public REVE_AGGREGATION_KUNRGRequest() {
        }
        
        public REVE_AGGREGATION_KUNRGRequest(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRG REVE_AGGREGATION_KUNRG) {
            this.REVE_AGGREGATION_KUNRG = REVE_AGGREGATION_KUNRG;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class REVE_AGGREGATION_KUNRGResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGResponse REVE_AGGREGATION_KUNRGResponse;
        
        public REVE_AGGREGATION_KUNRGResponse1() {
        }
        
        public REVE_AGGREGATION_KUNRGResponse1(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGResponse REVE_AGGREGATION_KUNRGResponse) {
            this.REVE_AGGREGATION_KUNRGResponse = REVE_AGGREGATION_KUNRGResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class REVE_AGGREGATION_KUNWE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] iT_KUNRGField;
        
        private string[] iT_KUNWEField;
        
        private string iV_KUNRG_FROMField;
        
        private string iV_KUNRG_TOField;
        
        private string iV_KUNWE_FROMField;
        
        private string iV_KUNWE_TOField;
        
        private ZPK_S_PERIOD iV_PERIOD_FROMField;
        
        private ZPK_S_PERIOD iV_PERIOD_TOField;
        
        private string iV_VKORGField;
        
        private string iV_VTWEGField;
        
        private string iV_WERKSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] IT_KUNRG {
            get {
                return this.iT_KUNRGField;
            }
            set {
                this.iT_KUNRGField = value;
                this.RaisePropertyChanged("IT_KUNRG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] IT_KUNWE {
            get {
                return this.iT_KUNWEField;
            }
            set {
                this.iT_KUNWEField = value;
                this.RaisePropertyChanged("IT_KUNWE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IV_KUNRG_FROM {
            get {
                return this.iV_KUNRG_FROMField;
            }
            set {
                this.iV_KUNRG_FROMField = value;
                this.RaisePropertyChanged("IV_KUNRG_FROM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IV_KUNRG_TO {
            get {
                return this.iV_KUNRG_TOField;
            }
            set {
                this.iV_KUNRG_TOField = value;
                this.RaisePropertyChanged("IV_KUNRG_TO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IV_KUNWE_FROM {
            get {
                return this.iV_KUNWE_FROMField;
            }
            set {
                this.iV_KUNWE_FROMField = value;
                this.RaisePropertyChanged("IV_KUNWE_FROM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string IV_KUNWE_TO {
            get {
                return this.iV_KUNWE_TOField;
            }
            set {
                this.iV_KUNWE_TOField = value;
                this.RaisePropertyChanged("IV_KUNWE_TO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public ZPK_S_PERIOD IV_PERIOD_FROM {
            get {
                return this.iV_PERIOD_FROMField;
            }
            set {
                this.iV_PERIOD_FROMField = value;
                this.RaisePropertyChanged("IV_PERIOD_FROM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public ZPK_S_PERIOD IV_PERIOD_TO {
            get {
                return this.iV_PERIOD_TOField;
            }
            set {
                this.iV_PERIOD_TOField = value;
                this.RaisePropertyChanged("IV_PERIOD_TO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string IV_VKORG {
            get {
                return this.iV_VKORGField;
            }
            set {
                this.iV_VKORGField = value;
                this.RaisePropertyChanged("IV_VKORG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string IV_VTWEG {
            get {
                return this.iV_VTWEGField;
            }
            set {
                this.iV_VTWEGField = value;
                this.RaisePropertyChanged("IV_VTWEG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string IV_WERKS {
            get {
                return this.iV_WERKSField;
            }
            set {
                this.iV_WERKSField = value;
                this.RaisePropertyChanged("IV_WERKS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class REVE_AGGREGATION_KUNWEResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZPK_S_REVE_KUNRG_RESULT_AQ10[] eT_AQ10Field;
        
        private ZPK_S_REVE_KUNRG_RESULT_AQ2[] eT_AQ2Field;
        
        private ZPK_S_REVE_KUNRG_RESULT_EXTWG[] eT_EXTWGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZPK_S_REVE_KUNRG_RESULT_AQ10[] ET_AQ10 {
            get {
                return this.eT_AQ10Field;
            }
            set {
                this.eT_AQ10Field = value;
                this.RaisePropertyChanged("ET_AQ10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZPK_S_REVE_KUNRG_RESULT_AQ2[] ET_AQ2 {
            get {
                return this.eT_AQ2Field;
            }
            set {
                this.eT_AQ2Field = value;
                this.RaisePropertyChanged("ET_AQ2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZPK_S_REVE_KUNRG_RESULT_EXTWG[] ET_EXTWG {
            get {
                return this.eT_EXTWGField;
            }
            set {
                this.eT_EXTWGField = value;
                this.RaisePropertyChanged("ET_EXTWG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class REVE_AGGREGATION_KUNWERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWE REVE_AGGREGATION_KUNWE;
        
        public REVE_AGGREGATION_KUNWERequest() {
        }
        
        public REVE_AGGREGATION_KUNWERequest(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWE REVE_AGGREGATION_KUNWE) {
            this.REVE_AGGREGATION_KUNWE = REVE_AGGREGATION_KUNWE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class REVE_AGGREGATION_KUNWEResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWEResponse REVE_AGGREGATION_KUNWEResponse;
        
        public REVE_AGGREGATION_KUNWEResponse1() {
        }
        
        public REVE_AGGREGATION_KUNWEResponse1(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWEResponse REVE_AGGREGATION_KUNWEResponse) {
            this.REVE_AGGREGATION_KUNWEResponse = REVE_AGGREGATION_KUNWEResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZPK_CRM_RAPORTYChannel : sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZPK_CRM_RAPORTYClient : System.ServiceModel.ClientBase<sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY>, sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY {
        
        public ZPK_CRM_RAPORTYClient() {
        }
        
        public ZPK_CRM_RAPORTYClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZPK_CRM_RAPORTYClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZPK_CRM_RAPORTYClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZPK_CRM_RAPORTYClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONResponse1 sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY.REVE_AGGREGATION(sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONRequest request) {
            return base.Channel.REVE_AGGREGATION(request);
        }
        
        public sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONResponse REVE_AGGREGATION(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION REVE_AGGREGATION1) {
            sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONRequest inValue = new sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONRequest();
            inValue.REVE_AGGREGATION = REVE_AGGREGATION1;
            sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONResponse1 retVal = ((sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY)(this)).REVE_AGGREGATION(inValue);
            return retVal.REVE_AGGREGATIONResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONResponse1> sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY.REVE_AGGREGATIONAsync(sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONRequest request) {
            return base.Channel.REVE_AGGREGATIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONResponse1> REVE_AGGREGATIONAsync(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION REVE_AGGREGATION) {
            sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONRequest inValue = new sap_soa_obroty.SOAPSAP.REVE_AGGREGATIONRequest();
            inValue.REVE_AGGREGATION = REVE_AGGREGATION;
            return ((sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY)(this)).REVE_AGGREGATIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGResponse1 sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY.REVE_AGGREGATION_KUNRG(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGRequest request) {
            return base.Channel.REVE_AGGREGATION_KUNRG(request);
        }
        
        public sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGResponse REVE_AGGREGATION_KUNRG(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRG REVE_AGGREGATION_KUNRG1) {
            sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGRequest inValue = new sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGRequest();
            inValue.REVE_AGGREGATION_KUNRG = REVE_AGGREGATION_KUNRG1;
            sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGResponse1 retVal = ((sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY)(this)).REVE_AGGREGATION_KUNRG(inValue);
            return retVal.REVE_AGGREGATION_KUNRGResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGResponse1> sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY.REVE_AGGREGATION_KUNRGAsync(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGRequest request) {
            return base.Channel.REVE_AGGREGATION_KUNRGAsync(request);
        }
        
        public System.Threading.Tasks.Task<sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGResponse1> REVE_AGGREGATION_KUNRGAsync(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRG REVE_AGGREGATION_KUNRG) {
            sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGRequest inValue = new sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNRGRequest();
            inValue.REVE_AGGREGATION_KUNRG = REVE_AGGREGATION_KUNRG;
            return ((sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY)(this)).REVE_AGGREGATION_KUNRGAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWEResponse1 sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY.REVE_AGGREGATION_KUNWE(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWERequest request) {
            return base.Channel.REVE_AGGREGATION_KUNWE(request);
        }
        
        public sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWEResponse REVE_AGGREGATION_KUNWE(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWE REVE_AGGREGATION_KUNWE1) {
            sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWERequest inValue = new sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWERequest();
            inValue.REVE_AGGREGATION_KUNWE = REVE_AGGREGATION_KUNWE1;
            sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWEResponse1 retVal = ((sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY)(this)).REVE_AGGREGATION_KUNWE(inValue);
            return retVal.REVE_AGGREGATION_KUNWEResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWEResponse1> sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY.REVE_AGGREGATION_KUNWEAsync(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWERequest request) {
            return base.Channel.REVE_AGGREGATION_KUNWEAsync(request);
        }
        
        public System.Threading.Tasks.Task<sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWEResponse1> REVE_AGGREGATION_KUNWEAsync(sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWE REVE_AGGREGATION_KUNWE) {
            sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWERequest inValue = new sap_soa_obroty.SOAPSAP.REVE_AGGREGATION_KUNWERequest();
            inValue.REVE_AGGREGATION_KUNWE = REVE_AGGREGATION_KUNWE;
            return ((sap_soa_obroty.SOAPSAP.ZPK_CRM_RAPORTY)(this)).REVE_AGGREGATION_KUNWEAsync(inValue);
        }
    }
}
