//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sap_soa_obroty.ZPK_S_CRM_ZPARRAP2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM")]
    public interface ZPK_S_CRM {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZPK_S_CRM:ZPK_S_CRM_ZPARRAP2Request", ReplyAction="urn:sap-com:document:sap:rfc:functions:ZPK_S_CRM:ZPK_S_CRM_ZPARRAP2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM_ZPARRAP2Response1 ZPK_S_CRM_ZPARRAP2(sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM_ZPARRAP2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZPK_S_CRM:ZPK_S_CRM_ZPARRAP2Request", ReplyAction="urn:sap-com:document:sap:rfc:functions:ZPK_S_CRM:ZPK_S_CRM_ZPARRAP2Response")]
        System.Threading.Tasks.Task<sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM_ZPARRAP2Response1> ZPK_S_CRM_ZPARRAP2Async(sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM_ZPARRAP2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPK_S_CRM_ZPARRAP2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dZIENDOField;
        
        private string dZIENODField;
        
        private string nRKASYField;
        
        private ZDZIEN_SKLEP_PARAGONY[] pARDZField;
        
        private ZDZIEN_SKLEP[] rESPONSEField;
        
        private WERKS zAKLADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DZIENDO {
            get {
                return this.dZIENDOField;
            }
            set {
                this.dZIENDOField = value;
                this.RaisePropertyChanged("DZIENDO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DZIENOD {
            get {
                return this.dZIENODField;
            }
            set {
                this.dZIENODField = value;
                this.RaisePropertyChanged("DZIENOD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NRKASY {
            get {
                return this.nRKASYField;
            }
            set {
                this.nRKASYField = value;
                this.RaisePropertyChanged("NRKASY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZDZIEN_SKLEP_PARAGONY[] PARDZ {
            get {
                return this.pARDZField;
            }
            set {
                this.pARDZField = value;
                this.RaisePropertyChanged("PARDZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZDZIEN_SKLEP[] RESPONSE {
            get {
                return this.rESPONSEField;
            }
            set {
                this.rESPONSEField = value;
                this.RaisePropertyChanged("RESPONSE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public WERKS ZAKLAD {
            get {
                return this.zAKLADField;
            }
            set {
                this.zAKLADField = value;
                this.RaisePropertyChanged("ZAKLAD");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZDZIEN_SKLEP_PARAGONY : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bSTNKField;
        
        private decimal bRUTTOField;
        
        private decimal vATField;
        
        private decimal nETTOField;
        
        private string wAERKField;
        
        private string zAKSIEGOWANEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BSTNK {
            get {
                return this.bSTNKField;
            }
            set {
                this.bSTNKField = value;
                this.RaisePropertyChanged("BSTNK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal BRUTTO {
            get {
                return this.bRUTTOField;
            }
            set {
                this.bRUTTOField = value;
                this.RaisePropertyChanged("BRUTTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal VAT {
            get {
                return this.vATField;
            }
            set {
                this.vATField = value;
                this.RaisePropertyChanged("VAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal NETTO {
            get {
                return this.nETTOField;
            }
            set {
                this.nETTOField = value;
                this.RaisePropertyChanged("NETTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string WAERK {
            get {
                return this.wAERKField;
            }
            set {
                this.wAERKField = value;
                this.RaisePropertyChanged("WAERK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZAKSIEGOWANE {
            get {
                return this.zAKSIEGOWANEField;
            }
            set {
                this.zAKSIEGOWANEField = value;
                this.RaisePropertyChanged("ZAKSIEGOWANE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class WERKS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wERKS1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WERKS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WERKS1 {
            get {
                return this.wERKS1Field;
            }
            set {
                this.wERKS1Field = value;
                this.RaisePropertyChanged("WERKS1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZDZIEN_SKLEP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string k_GField;
        
        private string zAKSIEGOWANEField;
        
        private string dATAField;
        
        private string nRKASYField;
        
        private string tAXM1Field;
        
        private string vTEXTField;
        
        private string sTAWKAVATField;
        
        private string wAERKField;
        
        private decimal nETWRField;
        
        private decimal mWSBPField;
        
        private decimal w_BRUTTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string K_G {
            get {
                return this.k_GField;
            }
            set {
                this.k_GField = value;
                this.RaisePropertyChanged("K_G");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZAKSIEGOWANE {
            get {
                return this.zAKSIEGOWANEField;
            }
            set {
                this.zAKSIEGOWANEField = value;
                this.RaisePropertyChanged("ZAKSIEGOWANE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DATA {
            get {
                return this.dATAField;
            }
            set {
                this.dATAField = value;
                this.RaisePropertyChanged("DATA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NRKASY {
            get {
                return this.nRKASYField;
            }
            set {
                this.nRKASYField = value;
                this.RaisePropertyChanged("NRKASY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TAXM1 {
            get {
                return this.tAXM1Field;
            }
            set {
                this.tAXM1Field = value;
                this.RaisePropertyChanged("TAXM1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string VTEXT {
            get {
                return this.vTEXTField;
            }
            set {
                this.vTEXTField = value;
                this.RaisePropertyChanged("VTEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string STAWKAVAT {
            get {
                return this.sTAWKAVATField;
            }
            set {
                this.sTAWKAVATField = value;
                this.RaisePropertyChanged("STAWKAVAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string WAERK {
            get {
                return this.wAERKField;
            }
            set {
                this.wAERKField = value;
                this.RaisePropertyChanged("WAERK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal NETWR {
            get {
                return this.nETWRField;
            }
            set {
                this.nETWRField = value;
                this.RaisePropertyChanged("NETWR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal MWSBP {
            get {
                return this.mWSBPField;
            }
            set {
                this.mWSBPField = value;
                this.RaisePropertyChanged("MWSBP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal W_BRUTTO {
            get {
                return this.w_BRUTTOField;
            }
            set {
                this.w_BRUTTOField = value;
                this.RaisePropertyChanged("W_BRUTTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZPK_S_CRM_ZPARRAP2Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int iLPARField;
        
        private int iLPOZField;
        
        private ZDZIEN_SKLEP_PARAGONY[] pARDZField;
        
        private ZDZIEN_SKLEP[] rESPONSEField;
        
        private decimal sRILPOZNAPARField;
        
        private decimal sRIL_NAPARField;
        
        private decimal sRWARTPARField;
        
        private decimal sRWARTPOZNAPARField;
        
        private decimal sRWARTSZTField;
        
        private decimal sUMA_ILField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ILPAR {
            get {
                return this.iLPARField;
            }
            set {
                this.iLPARField = value;
                this.RaisePropertyChanged("ILPAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int ILPOZ {
            get {
                return this.iLPOZField;
            }
            set {
                this.iLPOZField = value;
                this.RaisePropertyChanged("ILPOZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZDZIEN_SKLEP_PARAGONY[] PARDZ {
            get {
                return this.pARDZField;
            }
            set {
                this.pARDZField = value;
                this.RaisePropertyChanged("PARDZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZDZIEN_SKLEP[] RESPONSE {
            get {
                return this.rESPONSEField;
            }
            set {
                this.rESPONSEField = value;
                this.RaisePropertyChanged("RESPONSE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal SRILPOZNAPAR {
            get {
                return this.sRILPOZNAPARField;
            }
            set {
                this.sRILPOZNAPARField = value;
                this.RaisePropertyChanged("SRILPOZNAPAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal SRIL_NAPAR {
            get {
                return this.sRIL_NAPARField;
            }
            set {
                this.sRIL_NAPARField = value;
                this.RaisePropertyChanged("SRIL_NAPAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal SRWARTPAR {
            get {
                return this.sRWARTPARField;
            }
            set {
                this.sRWARTPARField = value;
                this.RaisePropertyChanged("SRWARTPAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal SRWARTPOZNAPAR {
            get {
                return this.sRWARTPOZNAPARField;
            }
            set {
                this.sRWARTPOZNAPARField = value;
                this.RaisePropertyChanged("SRWARTPOZNAPAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal SRWARTSZT {
            get {
                return this.sRWARTSZTField;
            }
            set {
                this.sRWARTSZTField = value;
                this.RaisePropertyChanged("SRWARTSZT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal SUMA_IL {
            get {
                return this.sUMA_ILField;
            }
            set {
                this.sUMA_ILField = value;
                this.RaisePropertyChanged("SUMA_IL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZPK_S_CRM_ZPARRAP2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM_ZPARRAP2 ZPK_S_CRM_ZPARRAP2;
        
        public ZPK_S_CRM_ZPARRAP2Request() {
        }
        
        public ZPK_S_CRM_ZPARRAP2Request(sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM_ZPARRAP2 ZPK_S_CRM_ZPARRAP2) {
            this.ZPK_S_CRM_ZPARRAP2 = ZPK_S_CRM_ZPARRAP2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZPK_S_CRM_ZPARRAP2Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM_ZPARRAP2Response ZPK_S_CRM_ZPARRAP2Response;
        
        public ZPK_S_CRM_ZPARRAP2Response1() {
        }
        
        public ZPK_S_CRM_ZPARRAP2Response1(sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM_ZPARRAP2Response ZPK_S_CRM_ZPARRAP2Response) {
            this.ZPK_S_CRM_ZPARRAP2Response = ZPK_S_CRM_ZPARRAP2Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZPK_S_CRMChannel : sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZPK_S_CRMClient : System.ServiceModel.ClientBase<sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM>, sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM {
        
        public ZPK_S_CRMClient() {
        }
        
        public ZPK_S_CRMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZPK_S_CRMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZPK_S_CRMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZPK_S_CRMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM_ZPARRAP2Response1 ZPK_S_CRM_ZPARRAP2(sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM_ZPARRAP2Request request) {
            return base.Channel.ZPK_S_CRM_ZPARRAP2(request);
        }
        
        public System.Threading.Tasks.Task<sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM_ZPARRAP2Response1> ZPK_S_CRM_ZPARRAP2Async(sap_soa_obroty.ZPK_S_CRM_ZPARRAP2.ZPK_S_CRM_ZPARRAP2Request request) {
            return base.Channel.ZPK_S_CRM_ZPARRAP2Async(request);
        }
    }
}
